[project]
name = "social-media-and-mental-health-impact"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "saloni1709", email = "2023pietcssaloni144@poornima.org" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.141.1",
    "joblib>=1.6.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "uvicorn>=0.53.0",
]

[project.scripts]
social-media-and-mental-health-impact = "social_media_and_mental_health_impact:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
